### ISSUE TITLE
broken link in README.md

### ISSUE THREAD

**Issue by wimel** [certusone/genki-4000#1]
In  [launch-once-genesis-collection-is-done](https://github.com/certusone/genki-4000#launch-once-genesis-collection-is-done) the link is broke, `error 404`  I think the correct is:
https://raw.githubusercontent.com/certusone/genki-4000/master/genesis.json

**Comment by hendrikhofstadt** [comment]
Thanks for looking into it.

The link will be genesis-final to avoid problems with caching on the old genesis.json
