### ISSUE TITLE
Test export to genesis.json upgrade of Genki 4000 to 4001

### ISSUE THREAD

**Issue by zmanian** [certusone/genki-4000#3]
This proposal will be submitted to governance on `Genki-4000`

In order to best prepare for the resumption of Game of Stakes after the holiday hiatus, it would be nice to test the ability to do an upgrade via the `--export --for-height-zero` mechanism.

I propose we do a hard fork upgrade based on an export of block `50,000` from `genki-4000`.

We would target the `genki-4001` to go live at 21:00 UTC on Dec 28th.

This would involve exporting `block 50,000` using the export fix pull request cherry picked as a hotfix to `v0.29.1`
https://github.com/cosmos/cosmos-sdk/pull/3189

**Comment by hendrikhofstadt** [comment]
Closed by #4
